input: {
    host: "/Users/changsun/Google Drive/VWData P8/Infrastructure/Infra_Installation/DataSharing_Repo_Branches/DataSharing_web/DataPartyStation/input",
    container: "/input"
    }

output: {
    host: "/Users/changsun/Google Drive/VWData P8/Infrastructure/Infra_Installation/DataSharing_Repo_Branches/DataSharing_web/DataPartyStation/output",
    container: "/output"
    }

inputVolume: {
    volumeName: "inputVolume",
    pathContainer: "/inputVolume",
        
    pathWebhost: "/inputVolume",
    pathEncDataInput: "encrypt_input.yaml",
    pathOverviewInput: "request.yaml",
    pathSignModelInput: "sign_model_input.yaml",
    pathPPKeysInput: "ppkeys_input.yaml"
    }