input: {
    host: "/Users/changsun/Google Drive/VWData P8/Infrastructure/Infra_Installation/DataSharing_Repo_Branches/DataSharing_web/TSEStation/input",
    container: "/input"
    }

output: {
    host: "/Users/changsun/Google Drive/VWData P8/Infrastructure/Infra_Installation/DataSharing_Repo_Branches/DataSharing_web/TSEStation/output",
    container: "/output"
    }

inputVolume: {
    volumeName: "inputVolume",
    pathContainer: "/inputVolume",
        
    pathWebhost: "/inputVolume",
    pathSecurityInput: "security_input.yaml",
    pathAnalysisInput: "analysis_input.yaml"
    }