input: {
    host: "/Users/changsun/GoogleDrive/VWData P8/Infrastructure/Infra_Installation/DataSharing_Repo_Branches/DataSharing_Web/DataPartyStation/EncData/input",
    container: "/input"
    }

output: {
    host: "/Users/changsun/GoogleDrive/VWData P8/Infrastructure/Infra_Installation/DataSharing_Repo_Branches/DataSharing_Web/DataPartyStation/EncData/output",
    container: "/output"
    }

inputVolume: {
    volumeName: "inputVolume",
    pathContainer: "/inputVolume",
        
    pathWebhost: "/inputVolume",
    pathInput: "encrypt_input.yaml"
    }